### ISSUE TITLE
Airplane mode doesn’t fill a color

### ISSUE THREAD

**Issue by Greigh** [NoisyFlake/MagmaEvo-support#10]
**Describe the bug**
Airplane mode toggle doesn’t fill colors. 

**To Reproduce**
1. Select color with color picker. 
2. Respring
3. Nothing changes. 

**Expected behavior**
Exactly like the other toggles. 

**Screenshots**
![CD90FFC0-0A4C-458D-A336-817D3E40D395](https://user-images.githubusercontent.com/57759540/72847157-f94f9480-3c6f-11ea-8d0c-c4e7bb281cc2.png)
![677A0A2E-52D4-4227-B294-B8906C2282DD](https://user-images.githubusercontent.com/57759540/72847181-02d8fc80-3c70-11ea-9403-405f71b16fcc.jpeg)

**iOS Version:**
12.4

**Device:**
XS Max

**Tweak list:**
https://ghostbin.co/paste/y6xky

**Comment by NoisyFlake** [comment]
You've only colored the enabled toggles. Click on "switch to disabled toggles" and configure the colors there as well.
