### ISSUE TITLE
Sliders missing on iOS 13

### ISSUE THREAD

**Issue by Potterd** [NoisyFlake/MagmaEvo-support#11]
Sliders are completely missing on iOS 13

Tested with Volume, Brightness, Tiny Volume, Tiny Brightness toggles. Tested with Magma EVO and Magma PRO - Sliders are missing with both.

Can supply additional details, if needed.

**Comment by NoisyFlake** [comment]
Please read the description of the tweak. Make sure that Reduce motion and Reduce transparency are disabled in your Accessibility settings.

**Comment by Potterd** [comment]
Works fine on iOS 12 without the need to set "Reduced Transparency" to "On".

Does not work at all on iOS 13 with "Reduced Motion" and "Reduced Transparency" set to "On" setting.  Slider background is not visible on iOS 13.

Comments apply to Magma PRO and Magma EVO.

**Comment by NoisyFlake** [comment]
Dude, you have to set them to ***OFF***...

**Comment by Potterd** [comment]
With all due respect, IMHO this should be classified as a bug and fixed.

Please consider:

Reduced Motion is major iOS functionality and is necessary to some for health reasons and to many for improved quality of the experience.

The slider background displays correctly as soon as the Magma tweak is disabled so it is clearly possible to have the slider background display correctly
 with Reduced Motion enabled.

I can’t think of another tweak that conflicts with stock iOS where this is considered to be normal - I’m sure you can fix this 😊
