### ISSUE TITLE
Incorrect Volume Slider Boarder color

### ISSUE THREAD

**Issue by owenainsworth** [NoisyFlake/MagmaEvo-support#12]
I use “CoolCC” to color the boarder of my cc toggles. When I use Magma Evo to color the fill and glyph of the volume slider it also colors the boarder overwriting the color I set coolcc to. This only happens on the volume slider and the brightness slider colors exactly as it should.

1. Set desired parameters in Magma Evo and CoolCC
2.Respring to apply settings
3.Open Control Center 

As with the brightness slider I expect the boarder color of the volume slider to be unaffected by Magma Evo

![F3B33B9D-5F1F-47CC-B28D-7DEE884E7293](https://user-images.githubusercontent.com/36117687/73143725-38605a00-4063-11ea-84b4-869217aa0575.jpeg)

iOS 13.3

iPhone X

applist
apt
apt-key
apt1.4
apt7
apt7-key
base
bash
berkeleydb
bzip2
ca-certificates
com.0neguy.opusclock
com.4nni3.coolcc
com.anthopak.switchshades
com.atwiiks.betterccxi
com.atwiiks.orion
com.bengiannis.complications
com.bingner.plutil
com.bingner.snappy
com.blackhole.gesto13
com.c1d3r.notchification
com.c1d3r.pagelabels
com.cemck.killx-pro
com.chpwn.iconsupport
com.ckosmic.brightcam
com.ckosmic.wiredock
com.cokepokes.libnotifications
com.cpdigitaldarkroom.itsevanesco
com.creaturecoding.crux
com.creaturecoding.libcspreferences
com.creaturecoding.shuffle
com.creaturesurvive.libcscolorpicker
com.daniel63194.clearfolders
com.exile90.icleanerpro
com.foxfort.aperturize
com.foxfort.camcontrolsx
com.foxfort.foxforttools
com.foxfort.libfoxfortutils
com.gilesgc.cccalc
com.gilshahar7.batterynotch
com.hackyouriphone.localiapstore13
com.ichitaso.powerselector11
com.imkpatil.cclinker
com.imkpatil.spotclearonclose
com.ivanobilenchi.icleanerdarktheme
com.jailbreak365.safeccmodules
com.jannikcrack.badgebar
com.junesiphone.xeninfo
com.kaneb.kbpreferences
com.kingpuffdaddi.hotspotqr
com.kurrt.gump
com.kurrt.lifeguard
com.laughingquoll.modulus
com.laughingquoll.noctis13
com.laughingquoll.prefixui
com.laughingquoll.sunflower
com.lema.michael.rhino
com.macciti.lotus
com.matchstic.xenhtml
com.midnightchips.ldrun
com.mrgcgamer.colormenotifs
com.mtac.no3dlines
com.muirey03.amandus
com.muirey03.centaur
com.muirey03.cr4shed
com.muirey03.flow
com.muirey03.iconsupportfix
com.muirey03.powermodule
com.muirey03.smallsiri
com.muirey03.zenith
com.noisyflake.magmaevo
com.noisyflake.windowhud
com.opa334.ccsupport
com.opa334.choicy
com.platykor.yobun
com.purdix.muze4
com.r333d.cylinder
com.restiveconch.actionbar
com.rpetrich.rocketbootstrap
com.rpgfarm.a-font
com.ryannair05.hidelabels13
com.saurik.substrate.safemode
com.shepgoba.colorscroll
com.shiftcmdk.pencilchargingindicator
com.spark.autounlockx
com.spark.circlesettings
com.spark.hidebarx
com.spark.libpackageinfo
com.spark.libsparkapplist
com.spark.libsparkcolourpicker
com.spark.lowbatterybanner
com.spark.nomoresmallapps
com.spark.snowboard
com.spark.snowboard.dock
com.spark.snowboard.effects
com.spark.snowboard.fonts
com.spark.snowboard.labels
com.spark.snowboard.masks
com.spark.snowboard.pagedots
com.spark.snowboard.presetextension
com.spark.snowboard.proceduralwallpapers
com.spark.snowboard.respringextension
com.spark.snowboard.settingsicons
com.spark.snowboard.statusbar
com.spark.snowboardapplication
com.spark.vesta
com.spicat.forceinpicture
com.spicat.recordntorch
com.stevsarm.gateau
com.synnyg.backupaz3
com.tigisoftware.filza
com.twickd.john-sklikas.3dbadgeclear
coreutils
coreutils-bin
cydia
cydia-lproj
darwintools
debianutils
diffutils
diskdev-cmds
dpkg
essential
file
findutils
firmware-sbin
gawk
gcrypt
gettext
gnupg
gnutls
grep
gzip
io.ominousness.ass
iokittools
jp.akusio.backgrounderaction13
jp.akusio.milkyway2
jp.ashikase.libcrashreport
jp.ashikase.libsymbolicate
jp.ashikase.techsupport
jp.r-plus.menusupport
jp.soh.iconator2
launchctl
ldid
libapt
libapt-pkg5.0
libassuan
libgmp10
libgpg-error
libidn2
libksba
libplist
libssl1.0
libssl1.1.1
libtasn1
libunistring
live.calicocat.pagebar
live.calicocat.statuspro
lz4
lzma
me.alfhaily.cercube
me.conorthedev.libconorthedev
me.conorthedev.pastel
me.gmoran.colorboard
me.kritanta.deadringer
me.kritanta.homeplus
me.midnightchips.snapback
me.nepeta.axon
me.nepeta.exo
me.nepeta.exobar
me.nepeta.libmitsuha
me.nepeta.libnepeta
me.nepeta.mitsuhainfinity
me.nepeta.mitsuhainfinity-homescreen
me.nepeta.mitsuhainfinity-lockscreen
me.nepeta.reachit
me.oatmealdome.dolphinios
mobilesubstrate
ncurses
ncurses5-libs
net.angelxwind.karenprefs
net.limneos.bioprotectxs
net.limneos.callbarxs
net.limneos.libbulletin
net.limneos.nfcwriterx
net.limneos.simpleactivationactions
nettle
npth
openssh
org.thebigboss.dismissprogress
org.thebigboss.libcolorpicker
org.thebigboss.repo.icons
p11-kit
p7zip
preferenceloader
profile.d
readline
rsync
ru.domo.cocoatop
se.nosskirneh.properlockgestures
se.nosskirneh.springartwork
sed
sh.litten.rose
shell-cmds
system-cmds
tar
uikittools
unrar
unzip
wget
ws.hbang.common
ws.hbang.libopener
xyz.henry.chromatic
xyz.royalapps.jellyfish
xyz.royalapps.rainbow
xyz.willy.zebra
xz
zip

This happens regardless of what color I choose

**Comment by NoisyFlake** [comment]
Considering that this only happens with CoolCC, it's safe to say that this is a conflict between those two tweaks. I doubt that there's much I can do about it though :/

**Comment by owenainsworth** [comment]
I was hoping this wasn’t true but thanks so much for the help, looks like it’s goodbye CoolCC!
