### ISSUE TITLE
Problems with betterccicons 

### ISSUE THREAD

**Issue by royorbs3** [NoisyFlake/MagmaEvo-support#13]
When using betterccicons the connectivity glyphs all get changed to white - whether toggled on or off, no matter what color they're set to. 

**To Reproduce**
Have both tweaks and disable connectivity modules in magma evo. Observe. 

**Expected behavior**
For betterccicons modules to display the colors they are set to. 

**Screenshots**

**iOS Version:**
13.2.2
**Device:**
iPhone.x
**Tweak list:**
Bunch of normal tweaks that everyone has

**Additional context**

**Comment by NoisyFlake** [comment]
Magma Evo is not compatible with BetterCCIcons.
