### ISSUE TITLE
Incompatibility with Gesto 

### ISSUE THREAD

**Issue by benjaminjoelhobbs** [NoisyFlake/MagmaEvo-support#15]
**Describe the bug**
When CC is activated normally it looks fine but activate it through Gesto and it will appear strange. That strange text appearance persists even with Norma activation after Gesto has been used once. The only way to remove it is to respring but then if Gesto is used, it will come right back. 

**To Reproduce**
1. Download and enable Gesto 
2. Activate CC normally (it will appear normal) 
3. Activate CC using Gesto, text alignment and text will appear strange. 
4. Activate CC normally and text will still appear strange until a respring. 

**Expected behavior**
A normal looking Control Center 

**Screenshots**
![55579CBF-2313-4E31-A9E7-87A141EE3255](https://user-images.githubusercontent.com/60387430/73417621-04409f80-42d6-11ea-94ba-824515689fd3.jpeg)

**iOS Version:**
13.3.1 but also 13.3

**Device:**
iPhone X 

**Tweak list:**
Either attach it as a text file or put it on e.g. pastebin.com (sorry didn’t know how to do those two): 

AppList: 1.5.15~beta1
APT (apt-key): 1.8.2-1
APT (libapt-pkg): 1.8.2-1
APT 0.7 Transitional (apt-key): 1:0
APT 1.4 Transitional: 1:0
APT Strict (lib): 1.8.2-1
APT: 1.8.2-3
Assuan: 2.5.1-1
AutoUnlockX: 1.0.12
Barmoji: 2020.3
Base Structure: 1-5
Berkeley DB: 6.2.32-1
BigBoss Icon Set: 1.0
Bourne-Again SHell: 5.0.3-2
bzip2: 1.0.6-1
CA Certs: 0.0.2
CCModules: 1.5-1
CCSupport: 1.2.2
Cephei: 1.14
Core Utilities (/bin): 8.31-1
Core Utilities: 8.31-1
Cydia Installer: 1.1.32~b23
Cydia Substrate: 0.9.7100
Cydia Translations: 1.1.32~b1
Darwin Tools: 1.1-1
Debian Packager: 1.19.7-1
Debian Utilities: 4.8.6-1
Diff Utilities: 3.6-1
diskdev-cmds: 593.221.1-1
DoubleCut: 0.5
file: 5.35-2
Find Utilities: 4.6.0-2
Flame: 1.3
Gesto13: 1.0.3
gettext: 0.19.8-1
GNU Cryptography: 1.8.3-1
GNU Multiple Precision Arithmetic Library: 6.1.2-1
GnuPG Errors: 1.32-1
GnuPG: 2.2.11-2
GnuTLS: 3.5.19-1
grep: 3.1-1
gzip: 1.9-1
HideBarX [Public]: 0.0.4
HomePlus Beta: 0.4.9-beta
iOS Firmware: 13.3.1
iPhone Firmware (/sbin): 0-1
Jellyfish: 1.3.3
KSBA: 1.3.5-1
Launch Daemon Controller: 23-1
libcolorpicker: 1.6.7
libidn2: 6.1.2-1
libplist: 2.0.0-2
libtasn1: 4.13-1
libunistring: 0.9.10-1
Link Identity Editor: 2:2.1.2+24497ae-1
LZ4: 1.7.5-1
LZMA Utils: 2:4.32.7-2
Magma Evo: 1.0.6
MathTeacher: 1.1.1
Mercury: 1.4.0
MsgPin: 0.0.2
Nettle: 3.4.1-1
New Curses: 5.9-1
New Curses: 6.1+20181013-1
New GNU Portable Threads: 1.6-1
OpenSSL 1.0 Libraries: 1.0.2s-1
p11-kit: 0.23.12-1
Peek Dark: 0.7
PreferenceLoader: 2.2.4~beta1
Profile Directory: 0-1
QuickLS: 1.2
readline: 8.0-1
Rewound: 1.1
RocketBootstrap: 1.0.7~beta3
Rose: 4.2.2
Saw: 1.4.0
sed: 4.5-1
shell-cmds: 118-8
Snappy: 1.3.0
SnowBoard: 1.2.86~Beta2
Substrate Safe Mode: 0.9.6003
system-cmds: 790.30.1-2
Tape Archive: 1.30-2
TweakReviewsDB: 0.5
UIKit Tools: 1.1.15-2
Viola Dark: 1.8
wget: 1.19.5-2
XZ Utils: 5.2.4-4
Zebra: 1.0.6
Zenith: 1.2.4-2

**Additional context**

**Comment by NoisyFlake** [comment]
Seeing as these labels appear only when using Gesto (and Magma is not the one creating them in the first place), I'd recommend to ask the developer of Gesto to fix this. It's probably not even possible to fix this in Magma.

**Comment by benjaminjoelhobbs** [comment]
The latest update fixed my problems with Gesto.
