### ISSUE TITLE
Color selection not showing on settings.

### ISSUE THREAD

**Issue by estebanGramajo** [NoisyFlake/MagmaEvo-support#17]
**Describe the bug**
There's no way to change color for the modules because the color selection circle is not there.
The On/Off switches works as expected tho.

**To Reproduce**
Go to settings > Magma Evo > Try to change a color

**Expected behavior**
I expected a way to select color.

**Screenshots**
![IMG_3035](https://user-images.githubusercontent.com/14099858/73883307-53805600-4829-11ea-9f3f-f92478f9bf8f.PNG)

**iOS Version:**
13.2.2

**Device:**
iPhone 7 Plus

**Tweak list:**
https://pastebin.com/SeMu1JFX

**Additional context**
...

**Comment by NoisyFlake** [comment]
Install libcolorpicker from BigBoss.
http://cydia.saurik.com/package/org.thebigboss.libcolorpicker/
