### ISSUE TITLE
Feature request 

### ISSUE THREAD

**Issue by iphizzle** [NoisyFlake/MagmaEvo-support#19]
Hello, can you add the ability to leave the status bar icons their default color? That way, a tweak like aerial or dapple can be used to theme the individual icons. Or maybe they will already overwrite magmas statusbar Coloring?

**Comment by NoisyFlake** [comment]
When no color is set for the status bar, Magma won’t color it.

**Comment by iphizzle** [comment]
Yes. But if you color it once. You can’t go back to default. I tried erasing the input but it returns

**Comment by NoisyFlake** [comment]
Long press on the name of the option you want to reset.

Von meinem iPhone gesendet

> Am 12.02.2020 um 00:10 schrieb iPhizzle <notifications@github.com>:
> 
> ﻿Yes. But if you color it once. You can’t go back to default. I tried erasing the input but it returns 
> 
> Sent from my iPhone
>

**Comment by iphizzle** [comment]
Hey, that worked! Good to know. I just updated to iOS 13 and that feature will come in handy!
