### ISSUE TITLE
Add button to set color back to Default

### ISSUE THREAD

**Issue by ThatsNiceGuy** [NoisyFlake/MagmaEvo-support#20]
Add a small button to set the color back to “Default Color” instead of having to reset all settings to set colors back to “Default Color”
![90F2F2F6-8390-41A1-B065-B28D0B2E6A2A](https://user-images.githubusercontent.com/10524728/74612984-95ca5280-50c7-11ea-8c1e-f3a48a2a1aaf.jpeg)

**Comment by NoisyFlake** [comment]
This is already a feature (which gets explained in the popup you see after installing Magma for the first time). Simply long-press on the setting you want to reset and it will revert back to the default color.
