### ISSUE TITLE
Sliders for Volume/Brightness Still don’t work

### ISSUE THREAD

**Issue by CzXe7** [NoisyFlake/MagmaEvo-support#24]
The volume and brightness sliders still do not have any background to them. I’ve disabled reduce transparency and blur motion and still not working. I’ve cleared old pref files and reinstalled. Still the same. No other tweaks installed, still does not work. iPhone Xr 13.3. Ive tried other people’s as well are your own presets and still do NOT work.

**Comment by NoisyFlake** [comment]
Do you have any other accessibility settings enabled? What version of Magma Evo do you have installed?

Also, next time please use the prefilled form to give all the necessary information. It's there for a reason.

**Comment by CzXe7** [comment]
I went ahead an restored my phone with succession and JBroke and reinstalled magma as my first tweak and everything seems to be working. Even after reinstalling my tweaks. Must’ve been a conflict from old preference files. Thanks but issue can now be solved.
