### ISSUE TITLE
Installing a prysm tweak removes one configuration from connectivity.

### ISSUE THREAD

**Issue by HappyJukeBox** [NoisyFlake/MagmaEvo-support#26]
**Describe the bug**

**To Reproduce**
1. Go to Installing a prysm tweak 
2. Click on Magma EVO-connectivity
3. Missing Rearrange Toggles Option

**Expected behavior**
I tried to rearrange the toggles but one of the Magma EVO settings is missing when I install Prysm Tweak.
When you delete a prysm tweak, the options reappear.

**Screenshots**
![KakaoTalk_20200301_213044675_02](https://user-images.githubusercontent.com/61653692/75625795-cef4dd80-5c04-11ea-9559-d4125e613125.jpg)
![KakaoTalk_20200301_213044675_01](https://user-images.githubusercontent.com/61653692/75625804-dcaa6300-5c04-11ea-9e84-ff5a7e2da8d3.png)

**iOS Version:**

13.3.1

**Device:**
iphone 7
**Tweak list:**

**Additional context**

**Comment by NoisyFlake** [comment]
This is intended behavior. Prysm has those toggles hardcoded, so it's not possible for Magma Evo to move them.

**Comment by HappyJukeBox** [comment]
Oh, I see. Thank you for solving your questions.

**Comment by marciocabelo** [comment]
Hello, I'm in trouble with magma evo version 1.2.3 on iphone X ios 13.4. every time i try to change the color of the control center he goes out and vomits to the home screen and i can't change i've done everything else i haven't been successful. I'm using the prysm
Hellp
