### ISSUE TITLE
Preset stuck, even when I reset and respring 

### ISSUE THREAD

**Issue by ewillyc** [NoisyFlake/MagmaEvo-support#27]
Preset “Ode to pro” keeps showing. I did “reset all settings” and respring, but the mentioned preset keeps showing.
I can not load any other preset because it keeps stuck with “Ode to pro”. 
I might have mess something when using iCleaner? 
Do I have to delete any file trough filza? 

Thanks

**Comment by NoisyFlake** [comment]
I'm not sure that I understand what the problem is. Can you maybe share some screenshots (or even better: a video) of what happens when you click on the preset and show the problem?

**Comment by NoisyFlake** [comment]
No further reply.
