### ISSUE TITLE
Enabling Reduce Motion causes volume/brightness sliders to not show when increasing or decreasing.

### ISSUE THREAD

**Issue by 11five** [NoisyFlake/MagmaEvo-support#28]
In settings when enabling Reduce motion in accessibility, the volume&btightness increase/decrease indicators don’t show. Picture provided shows the brightness is at max, you can tell my the sun glyph 
![FAE82C28-E753-4D42-9852-488605967941](https://user-images.githubusercontent.com/55474736/76158497-b137e480-60ec-11ea-8f19-5e7f7ff6b990.png)
indicator.

**Comment by NoisyFlake** [comment]
Yes, this is mentioned in the tweak description.
