### ISSUE TITLE
Support for independent color choosing 

### ISSUE THREAD

**Issue by CySxL** [NoisyFlake/MagmaEvo-support#3]
1.Support for independent overlay color choosing, like the following screenshot 
![391F73FF-5CAC-4DC3-80AC-B7744BEB7E47](https://user-images.githubusercontent.com/15531137/72408888-26e39c00-379f-11ea-8f6e-4e39588e5f8f.jpeg) (image from reddit)
It means in disabled/enabled mode, u can choose overlay color independently!

2.Option to turn on/off dynamic glyph coloring function, or even can choose the glyph color yourself while toggle enabled.

3.Cowbell support. 
![9C343C42-4A62-435F-92A2-607B2E5BC407](https://user-images.githubusercontent.com/15531137/72409068-b0936980-379f-11ea-909f-24fbd66ff2c8.png)
(It’s ok to know that not going support cowbell because its really weird in code.)

**Comment by NoisyFlake** [comment]
Independent overlay color won't be implemented as I can't think of a way to implement settings for this that wouldn't clutter the already packed preferences, making them more hard to use for endusers.

The other two are on my to-do list and might be implemented eventually.
