### ISSUE TITLE
Miscoloring of NextUp2’s song title and artist

### ISSUE THREAD

**Issue by loulouboy** [NoisyFlake/MagmaEvo-support#30]
When you select a song, and NextUp2 shows the song that will be playing next (see first picture), the title and artist match (due to color flow). Although, when you press the “X” to move up the queue, Magma’s presets take over and the color matching no longer works (see second picture). 

https://imgur.com/a/NuvBjhv (1)
https://imgur.com/a/vjejqcK (2)

Any help is appreciated, thank you!

Installed tweaks: https://pastebin.com/iEtS8B5t

iPhone XS Max, IOS 13.3

**Comment by NoisyFlake** [comment]
This is indeed a bug. Magma's coloring shouldn't take effec if you don't have it enabled for the lockscreen.

Will be fixed in the next version.

**Comment by loulouboy** [comment]
Awesome! Thank you so much!!!

**Comment by loulouboy** [comment]
Hello! Your recent update has fixed the issue! Thank you so much!
