### ISSUE TITLE
Artwork preview will not become transparent. 

### ISSUE THREAD

**Issue by 9kag** [NoisyFlake/MagmaEvo-support#32]
**Describe the bug**
After the latest update I can no longer make the artwork preview transparent. I had to downgrade.

**To Reproduce**
1. Artwork preview 
2. Change the colour to transparent 

**Expected behavior**
The color should be transparent but it does not turn transparent. 

**Screenshots**

**iOS Version:** iOS 13.3

**Device:** iPhone X

**Tweak list:**
Either attach it as a text file or put it on e.g. pastebin.com

**Additional context**

**Comment by NoisyFlake** [comment]
I assume you're talking about Prysm? If yes, this will be re-added in the next version.

**Comment by 9kag** [comment]
Yes the Prysm artwork cannot be made transparent anymore. It wasn’t the
case before.

**Comment by NoisyFlake** [comment]
Fixed with v1.2.3
