### ISSUE TITLE
I can't change the races with magma evo on the prysm

### ISSUE THREAD

**Issue by marciocabelo** [NoisyFlake/MagmaEvo-support#35]
the error persists every time I adjust the colors of the control channel it goes back to the home screen

**To Reproduce**
1. Go to. Connctivity
2. Click on global color 
3. Scroll down to when I try to change the color of the wifi it comes out
4. See error there you go back to the home screen and I don't want to change the color, nor the wifi, celluar data, etc.

**Expected behavior**

I formatted the iphone from the beginning, redid the jailbreak, even so I can't use the magma evo, for nothing I can't even adjust the colors help me

**Screenshots**
I can't send a photo because it doesn't even arrive at the moment I'm going to change the color, when you click to adjust the color it goes back to the home screen

**iOS Version:** 13.4

**Device:** iPhone X

**Tweak list:**
as I said I have nothing but the magma evo installed already now to know if it is incotibility with some tweark but still nothing,

**Additional context**
I don't know what to do anymore I have already tried everything I installed libcolorpick from repo bigboss as it says in the information when buying tweark
help me i bought tweark and i really want to use

**Comment by NoisyFlake** [comment]
libcolorpicker is not updated for 13.4 and therefore crashes. That's not something that can be fixed in Magma.
