### ISSUE TITLE
Color picker on Ipad in Landscape misaligned, cant see sliders.

### ISSUE THREAD

**Issue by IammGrooot** [NoisyFlake/MagmaEvo-support#36]
**Describe the bug** 
Color Picker is miss aligned

**To Reproduce**

**Expected behavior**
Colorpicker centered on settings tab so I can use its features.

[**Screenshots**](url)
![IMG_0153](https://user-images.githubusercontent.com/61368526/78270640-f1a63a80-74bf-11ea-9947-a76c78f9315f.png)

**iOS Version:**
13.3
**Device:**
Ipad pro 2018
**Tweak list:**

3DBadgeClear: 1.6.4
7-zip (POSIX): 16.02-1
Ace High Sierra: 5.1
AnimationsBeFastPlus: 4.5
AppList: 1.5.15
AppSync Unified: 72.0
APT (apt-key): 1.8.2-1
APT (libapt-pkg): 1.8.2-1
APT 1.4 Transitional: 1:0
APT Strict (lib): 1.8.2-1
APT: 1.8.2-3
Assuan: 2.5.1-1
Axon: 1.0
BackgrounderAction2 for CCSupport: 0.1.4
BadgeBar: 1.1.7.1
Barmoji: 2020.3.1
Base Structure: 1-5
Berkeley DB: 6.2.32-1
BetterCCXI (Weather Addon): 1.0.3
BetterCCXI: 1.6.0
BetterMultitasking: 1.2.0
BigBoss Icon Set: 1.0
BigPiPEnergy: 1.3.0
Bohemic NOIR: 1.0.3
Bourne-Again SHell: 5.0.3-2
bzip2: 1.0.6-1
CA Certs: 0.0.2
CCModules: 1.5-1
CCSupport: 1.2.2
CenteredLargeTitles: 1.0.4
Cephei: 1.14
ColorFlow 5 (iOS 13): 1.0.3
ColorfulGoose: 1.2
Core Utilities (/bin): 8.31-1
Core Utilities: 8.31-1
CPDD Connect: 4.1.2
crux: 1.0.0
Cydia Installer: 1.1.32~b25
Cydia Translations: 1.1.32~b1
Darwin Tools: 1.1-1
Debian Packager: 1.19.7-1
Debian Utilities: 4.8.6-1
debugserver-10: 10.0.0~svn-20191106+dcaf932-1
debugserver: 10-1
Diff Utilities: 3.6-1
diskdev-cmds: 593.221.1-1
Dock13: 0.0.1
EQE: 2.1.1
Evanesco!: 2020.5.1
EW.WdgtPack.8: 2.0-1
file: 5.35-2
Filza File Manager: 3.7.2
Find Utilities: 4.6.0-2
Flame: 1.3
Flex 3 Beta: 1:3~Beta86
Foldy: 1.1
FoxFort Tools: 1.0.16
Frame: 2.0.0-beta2
FUGap: 2.2.4
Gateau: 1.55
gettext: 0.19.8-1
GNU Cryptography: 1.8.3-1
GNU Multiple Precision Arithmetic Library: 6.1.2-1
GnuPG Errors: 1.32-1
GnuPG: 2.2.11-2
GnuTLS: 3.5.19-1
grep: 3.1-1
Gump: 2.0.0
gzip: 1.9-1
HideBarX [Public]: 0.0.4
iCleaner Pro: 7.8.0
IconState: 0.1.0
IconSupport: 1.11.1
IconSupportFix: 1.0.0
iOS Firmware: 13.3
iPhone Firmware (/sbin): 0-1
Jailbreak Resources: 1.0~rc1
jbctl: 0.2.3-1
Juice: 0.0.2~Beta1
Kairos 3: 2019.1~beta5
KarenLocalizer: 1.0.5
KarenPrefs: 1.5
KSBA: 1.3.5-1
LatchKey: 2.1.2
Launch Daemon Controller: 23-1
libclang-cpp10: 10.0.0~svn-20191106+dcaf932-1
libcolorpicker: 1.6.7
libconorthedev: 1.1
libCSColorPicker: 1.0.3
libCSPreferences: 1.3.4
libfoxfortsplash: 1.1.2
libfoxfortutils: 1.0.15
libidn2: 6.1.2-1
libimagepicker: 1.0.4
libllvm10: 10.0.0~svn-20191106+dcaf932-1
libMRYIPC: 1.0
libpackageinfo (SparkDev): 1.1.4
libplist: 2.0.0-2
libSparkAppList: 1.0.7
libsparkcolourpicker: 0.0.26
libSparkMessage: 1.0.0
libtasn1: 4.13-1
libunistring: 0.9.10-1
Limelight: 1.9.6
Link Identity Editor: 2:2.1.2+24497ae-1
Lower: 1.5.1
LPMPad: 1.0
LZ4: 1.7.5-1
LZMA Utils: 2:4.32.7-2
Magma Evo: 1.2.3
MilkyWay2: 0.2.0-alpha
MobileGoose: 1.3
MobileGooseModule: 1.0.1
Nettle: 3.4.1-1
New Curses: 5.9-1
New Curses: 6.1+20181013-1
New GNU Portable Threads: 1.6-1
OpenSSL 1.0 Libraries: 1.0.2s-1
p11-kit: 0.23.12-1
PreferenceLoader: 2.2.4
PrefixUI: 1.2.6
Profile Directory: 0-1
Quart Beta 4: 0.4
readline: 8.0-1
ReProvision: 0.5.2~EOL
RocketBootstrap: 1.0.7
Ryu_003: 1.0
Search BarX: 1.3
sed: 4.5-1
shell-cmds: 118-8
ShortcutEnabler: 1.2.1
shuffle: 1.1.4
SkinnySettings: 1.3.7
SmokeBoard Pro: 2.3
SnowBoard Settings Icons Extension: 1.0.18~Beta1
SnowBoard: 1.2.87~Beta2
Substitute Support Package: 0.1~b3
Substrate Safe Mode: 0.9.6003
SwipeForMore: 1.1.7
System Memory Reset Fix: 2.0
system-cmds: 790.30.1-2
Tape Archive: 1.30-2
Trust Cache Injector: 0.4~b5
Turkey: 0.0.1
UIKit Tools: 1.1.15-2
unrar: 5.6.4-1
unzip: 6.0+deb9u1-1
Xen HTML: 1.1.4~release
XenInfo: 2.2.9
XZ Utils: 5.2.4-4
zip: 2.32-1

**Additional context**

**Comment by NoisyFlake** [comment]
This is libcolorpickers problem, not Magmas. There is nothing I can do about it. 

I'm thinking about switching to another color picker anyway. In the meantime, please adjust your colors in portrait mode, it should work this way.
