### ISSUE TITLE
Settings Crashes whenever libcolorpicker is opened

### ISSUE THREAD

**Issue by cr16blue8** [NoisyFlake/MagmaEvo-support#38]
**Describe the bug**
Whenever I open the color picker (I assume it is libcolorpicker), my settings app crashes.  This is the case with all tweaks using libcolorpicker.

**To Reproduce**
1. Install a tweak with libcolorpicker
2. go to the settings and select the colorpicker
3. settings crashes

**Expected behavior**
I am able to select the color and it does not crash

**iOS Version:**
13.4

**Device:**
iPhone X

**Tweak list:**
https://pastebin.com/ie546hu7

**Additional context**
crash report: 
https://pastebin.com/NCDkZq50

**Comment by cr16blue8** [comment]
I was able to get it to work with Alderiz color picker, but given that most devs used libcolorpicker, I wanted to let you know.

**Comment by NoisyFlake** [comment]
libcolorpicker is not updated for 13.4 yet.

**Comment by cr16blue8** [comment]
That is not the issue.  Libcolorpicker was previously working for me on my 13.4 and 13.4.1 builds.  I am only now getting this error on my device after downgrading back to 13.4.  The only functionality that was not working for libcolorpicker beforehand was the ability to type in a hex value - that would cause preferences to crash.  This is not the case now though.

**Comment by NoisyFlake** [comment]
You probably have something in your clipboard which causes libcolorpicker to ask if you want to use this as a color, thus crashing on 13.4. But Magma will receive an update that uses a different colorpicker soon anyway.

**Comment by cr16blue8** [comment]
Interesting.  My clipboard is clear, and the issue also occured when I had my sources (from flame) copied in my clipboard.  Anyway, I am glad that you are using a different color picker and best of luck in implementing it.

**Comment by NoisyFlake** [comment]
If you've never used libcolorpicker on that device, it will display a welcome alert (which crashes, due to libcolorpicker using an outdated method for displaying those alerts).

**Comment by cr16blue8** [comment]
That makes perfect given the error.  I had no clue that it tried to show a welcome notification as I did not have this issue prior to restoring my phone.  Also, wasn't UIAlertView deprecated in iOS 9?  Is there a reason why libcolorpicker has not been updated to use UIAlertController?

**Comment by NoisyFlake** [comment]
Yes, it has been deprecated for a long time, and only with 13.4 Apple made it actually throw an Exception. No idea why the author hasn't changed this so far, but I guess he isn't even interested in it anymore, since there is no sign of an update for 13.4 either.

**Comment by cr16blue8** [comment]
Good to know.  Thank you.
