### ISSUE TITLE
Magma Evo breaks WeatherVane

### ISSUE THREAD

**Issue by bendrank** [NoisyFlake/MagmaEvo-support#4]
**Describe the bug**
Since upgrading to Magma Evo from Magma Pro, the WeatherVane interface can’t be activated (which is typically done by expanding the connectivity tray and long pressing on either the Bluetooth icon or WiFi icon)

**To Reproduce**
1. Install weathervane tweak
2. Expand connectivity tray. Long press on either Bluetooth or WiFi icon in CC
3. Nothing happens :(

**Expected behavior**
On Magma Pro, the weathervane interface would pop up normally. The weathervane interface allows connecting to either a Bluetooth device or WiFi network from CC without having to launch settings app. 

**iOS Version:**
iOS 12.1.2
NOTE: I think iOS 13 eliminates the need for WeatherVane by implementing this function natively, but alas I am still on iOS 12 for irrelevant reasons. 

**Device:**
iPhone X

Additional Info:
Nothing has changed from yesterday to today except for my replacing Magma Pro with Evo.

**Comment by NoisyFlake** [comment]
I'll try to fix this in the next update, though I can't promise anything right now until I test it myself.

**Comment by NoisyFlake** [comment]
This issue was fixed in v1.0.6 which was just uploaded to Packix and should be live soon.
