### ISSUE TITLE
Lost Compatibility with Togglow

### ISSUE THREAD

**Issue by Potterd** [NoisyFlake/MagmaEvo-support#5]
Magma Pro is compatible with Togglow on my device running iOS 12.4.  Togglow creates colored rings around the connectivity toggles (different colors for enable/disable) and also allows the "selected" background to be removed for the Other Modules.  The 1st attachment is with Magma Pro and Togglow.  After reviewing your package info for Magma EVO , I decided to upgrade even though it did not appear to have significant new functionality.  I like the new Magma EVO preferences interface and would like to be using your latest version but this version is no longer compatible with Togglow as seen in the 2nd attachment which is with Magma EVO installed with Togglow.

So I'm hoping that you will fix Magma EVO so that it continues to be compatible with Togglow, like Magma Pro.  Magma Pro  appears to work fine with Togglow, which is a very cool tweak IMHO.

Thanks for considering .....

![IMG_0687(1)](https://user-images.githubusercontent.com/2848810/72649414-832af500-3932-11ea-9c59-49f192262701.PNG)

![IMG_0688(1)](https://user-images.githubusercontent.com/2848810/72649421-88883f80-3932-11ea-9a1f-2c820d428edf.PNG)

**Comment by NoisyFlake** [comment]
It's not really possible to fix this incompatibility. The fact that Magma Pro kinda worked with Togglow was more of a coincidence than actual intended behavior. Due to the way Magma Evo works, it's not really possible to restore compatibility with Togglow.

If you want a refund for Magma Evo because of this, feel free to create a request through Packix/Twickd and I'll take care of it.

**Comment by Potterd** [comment]
First of all I want to congratulate on a great design for Magma EVO – definitely one of the best tweaks around and a great improvement over Magma Pro.

 

I do like the “colored ring” effect that is possible with Togglow and feel that it is unfortunate to lose that functionality, so I will make the following suggestion for your consideration:

 

For Connectivity toggles you have the “Glyth Only” setting where the selected colors are applied to the Glyphs and you have the “Regular” setting where the selected colors are applied to the background and you use default colors for the glyphs.  You could add a 3rd option for “Rings Only” where you apply the selected colors to the rings and use default colors (all white) for the glyphs.  I think this 3rd option would fit nicely with how you have redesigned the UI and would allow for a Togglow-like display which looks cool IMHO.

 

Regards,

 

David Potter

DPotter Consulting Inc

(415) 485-5876 (office)

(415) 608-7797 (mobile)

 <mailto:David@dpotterconsulting.com> David@dpotterconsulting.com

 

You can view me on LinkedIn:  <http://www.linkedin.com/in/dpotterconsulting> www.linkedin.com/in/dpotterconsulting
