### ISSUE TITLE
Magma PRO/EVO Connectivity icon issue

### ISSUE THREAD

**Issue by Potterd** [NoisyFlake/MagmaEvo-support#6]
This issue affects Connectivity icons for both Magma Pro and Magma EVO.  iOS has different icons for Wifi and Bluetooth for "enabled" and "disabled" states but when Magma Pro or Magma EVO are installed and active, only the "enabled" state icons are displayed.

It would be nice to maintain the functionality for the "disabled" state icons in these tweaks.  Screenshots of "Disabled" states are included in the attached images using Magma Pro and Togglow.  The 1st image is in airplane mode with with Magma Pro enabled and the 2nd image is in airplane mode with Magma Pro disabled. 

Appreciate your consideration to fix both programs ..... 

![IMG_0693(1)](https://user-images.githubusercontent.com/2848810/72651498-511c9180-3938-11ea-9790-b0d29625c5bb.PNG)

![IMG_0692(1)](https://user-images.githubusercontent.com/2848810/72651504-57127280-3938-11ea-95d3-f156b49296ba.PNG)

**Comment by NoisyFlake** [comment]
This is actually kind of intentional, as most users wished for a cleaner and unified appearance of those symbols. The other icons don't have an additional icon for the disabled state, so most users thought it's not necessary to keep the original iOS icons intact.
