### ISSUE TITLE
coloring airplay icon doesnt work on a12

### ISSUE THREAD

**Issue by Xp3r10n** [NoisyFlake/MagmaEvo-support#7]
sorry to be a pain, but magma evo doesn't color the airplay icon in my cc,, it remains blue.
i'm running magma evo 1.0.5 on ios 12.1.2, iphone xr.

would greatly appreciate a fix for this :)

![Photo 19-1-20, 12 43 48 pm](https://user-images.githubusercontent.com/36470794/72673666-9916f200-3ab9-11ea-9d41-c73d5b5b3bc6.jpg)

![Photo 19-1-20, 12 46 49 pm](https://user-images.githubusercontent.com/36470794/72673688-d9767000-3ab9-11ea-860e-7650d148787d.jpg)

**Comment by NoisyFlake** [comment]
You're right, I forgot to test the AirPlay icon on iOS 12. Looks like my implementation only works on iOS 13. Will be fixed with the next update! :)

**Comment by NoisyFlake** [comment]
This issue was fixed in v1.0.6 which was just uploaded to Packix and should be live soon.
