### ISSUE TITLE
Colored Ring Enhancement Suggestion

### ISSUE THREAD

**Issue by Potterd** [NoisyFlake/MagmaEvo-support#8]
First of all I want to congratulate on a great design for Magma EVO – definitely one of the best tweaks around and a great improvement over Magma Pro.

I do like the “colored ring” effect that is possible with Togglow and feel that it is unfortunate to lose that functionality, so I will make the following suggestion for your consideration:

For Connectivity toggles you have the “Glyth Only” setting where the selected colors are applied to the Glyphs and you have the “Regular” setting where the selected colors are applied to the background and you use default colors for the glyphs.  You could add a 3rd option for “Rings Only” where you apply the selected colors to the rings and use default colors (all white) for the glyphs.  I think this 3rd option would fit nicely with how you have redesigned the UI and would allow for a Togglow-like display which looks cool IMHO.

Screenshot is using Magma Pro and Togglow.  With this enhancement the same type of display would be possible with Magma EVO alone (without the use of Togglow).

![IMG_0708](https://user-images.githubusercontent.com/2848810/72674509-67a41500-3a2c-11ea-98af-5a702f7f872c.PNG)

**Comment by NoisyFlake** [comment]
I probably won't add this, considering it would be just like Togglow. The community is known for not being very appreciative for implementing features that other tweaks already have - especially if the tweak is not free.

**Comment by Potterd** [comment]
This makes sense due to the fact that you would be incorporating another dev’s ideas into your paid tweak, so I understand your thinking here.

 

What I still don’t understand is why it is OK to break the compatibility with Togglow, and I think this action would also be frowned upon by the community.  Users of both tweaks are now forced to choose between them and since you have much more functionality in Magma EVO, the choice for most users will be to probably stop using Togglow.  Since Magma Pro and Togglow work together, it is surely doable to restore this compatibility.

 

It’s true both tweaks are designed for the Control Center and both operate on the Connectivity Toggles, but beyond that they provide different functionality and have a history of working well together.  Restoring this compatibility is the right thing to do IMHO to show appropriate respect for devs and users.

 

With all due respect and for your further consideration …..

 

Regards, 

 

David Potter

DPotter Consulting Inc

(415) 485-5876 (office)

(415) 608-7797 (mobile)

 <mailto:David@dpotterconsulting.com> David@dpotterconsulting.com

 

You can view me on LinkedIn:  <http://www.linkedin.com/in/dpotterconsulting> www.linkedin.com/in/dpotterconsulting
