### ISSUE TITLE
Disables QuickCC on iOS 12

### ISSUE THREAD

**Issue by LaToyaShaniqua** [NoisyFlake/MagmaEvo-support#9]
iPhone XS Max on iOS 12.1.1 here via unc0ver....

QuickCC does not work while magma evo is installed at the same time. This was not the case when using magma pro.

**Comment by NoisyFlake** [comment]
Magma Evo is completely different from Magma Pro, so it's not something that "broke during the update", it's a completely different piece of software. I'll take a look at it when I try to fix the WeatherVane bug.

**Comment by NoisyFlake** [comment]
This issue was fixed in v1.0.6 which was just uploaded to Packix and should be live soon.
